flask-app/webui/ApiCommunication/__init__.py
"""
deze map bevat alle methoden en klassen die kunnen gebruikt worden om met de bewell api te communiceren
"""

flask-app/webui/__init__.py
import os
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
DB_NAME = "database.db"


class Patient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    afdeling = db.Column(db.Integer)
    kamer = db.Column(db.Integer)
    familienaam = db.Column(db.String(50))
    voornaam = db.Column(db.String(50))
    geboortedatum = db.Column(db.String(10))
    dieet = db.Column(db.String(50))
    laatste_bevraging = db.Column(db.String(10))


def create_app():
    app = Flask(__name__)
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    db.init_app(app)

    # generate secret key and set it in the app
    app.secret_key = os.urandom(24)

    from .views import views

    app.register_blueprint(views, url_prefix="/")

    with app.app_context():
        db.create_all()

    return app


def create_database(app):
    if not path.exists("instance/" + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

flask-app/webui/views.py
from functools import reduce
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import Patient, db
from sqlalchemy import desc, asc
from faker import Faker
from datetime import date
from random import *
from .ApiCommunication import Messages, Patienten
from .ApiCommunication.Models2 import Content, MessagePost
from .FrontendModels.Patient import Patient

"""
hier staan alle routes van de api
"""

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return render_template("home.html")


@views.route("/usecase1")
def usecase1():
    return render_template("usecase1.html")


# vraagt alle patienten op, bouwt de template op en geeft ze terug
@views.route("/usecase2", methods=["GET"])
def usecase2():
    # all_patients = Patient.query.order_by(desc(Patient.id)).all()
    # vraagt alle patienten op
    all_patients = list(
        map(
            lambda patient: Patient.fromBewellApiModel(patient),
            Patienten.getPatienten(""),
        )
    )
    # bouwt de template ne geeft ze terug
    return render_template("usecase2.html", patients=all_patients)


@views.route("/addDummyData", methods=["POST"])
def addDummyData():
    if request.method == "POST":
        fakerProvider = Faker()
        rnd = Random()
        for i in range(30):
            new_patient = Patient(
                afdeling=rnd.randint(1, 5),
                kamer=rnd.randint(1, 5),
                familienaam=fakerProvider.last_name(),
                voornaam=fakerProvider.first_name(),
                geboortedatum=fakerProvider.date_of_birth().__str__(),
                dieet="Normaal",
                laatste_bevraging=date.today().__str__(),
            )
            db.session.add(new_patient)
            db.session.commit()
    return redirect(url_for("views.usecase2"))


@views.route("/deleteData", methods=["POST"])
def deleteData():
    if request.method == "POST":
        Patient.query.delete()
        db.session.commit()
    return redirect(url_for("views.usecase2"))


@views.route("/deleteRecord/<patientId>", methods=["POST"])
def deleteRecord(patientId):
    if request.method == "POST":
        patient = Patient.query.get(patientId)
        if patient:
            db.session.delete(patient)
            db.session.commit()
    return redirect(url_for("views.usecase2"))


# vraagt alle patienten op gefilterd op basis van het 'searchquery veld van de meegestuurde form en bouwt dan de usecase2.html template op met de gevonden patienten'
@views.route("/filterData/", methods=["post"])
def filterData():
    import re

    # neemt de searchquery uit de meegestuurde form en converteerd hem naar het juiste formaat
    searchQuery = request.form.get("searchQuery").__str__().strip()
    search = "{}".format(searchQuery.lower().strip())
    print("searching for: ", search)
    # filtered_patients = Patient.query.filter(Patient.voornaam.like(search)|
    #                                          Patient.familienaam.like(search)
    #                                          ).all()
    # filterd de patienten op basis van de searchquery: als de searchquery voornaam of familienaam of een combinatie van beide bevat zal deze patient in filtered patients worden gestoken
    filtered_patients = list(
        filter(
            lambda patient: search
            in patient.first_name.lower() + " " + patient.last_name.lower(),
            map(
                lambda patient: Patient.fromBewellApiModel(patient),
                Patienten.getPatienten(""),
            ),
        )
    )
    print("de gefilterde patienten: ", filtered_patients)
    return render_template(
        "usecase2.html", patients=filtered_patients, searchValue=searchQuery
    )


# geeft de template terug om een nieuwe patient aan te maken
@views.route("/addPatientRequest/", methods=["GET"])
def addPatientRequest():
    return render_template("addNewPatient.html", views=views)


# deze post route gebruikt de data in de meegestuurde form om een nieuwe patient aan te maken
@views.route("/newPatient", methods=["POST"])
def newPatient():
    try:
        patientToAdd = Patient(
            afdeling=int(request.form["afdeling"]),
            kamer=int(request.form["kamer"]),
            familienaam=request.form["familienaam"],
            voornaam=request.form["voornaam"],
            geboortedatum=request.form["geboortedatum"],
            dieet=request.form["dieet"],
            laatste_bevraging=request.form.get("laatste_bevraging"),
        )
        db.session.add(patientToAdd)
        db.session.commit()
        flash("patient is toegevoegd")
        return redirect(url_for("views.usecase2"))
    except ValueError:
        flash("geef een correcte waarde in")
        return redirect(url_for("views.addPatientRequest"))


# geeft de template terug om een nieuw berichtje aan te maken
@views.route("/getNewMessage", methods=["get"])
def getNewMessage():
    PatientNamen = list(
        map(
            lambda patient: {
                "id": patient.id,
                "name": f"{patient.first_name}_{patient.last_name}",
            },
            Patienten.getPatienten(""),
        )
    )
    mostRecentMessageRaw = Messages.getMostRecentMessage()
    lastMessage = {
        "inhoud": mostRecentMessageRaw.text,
        "ontvanger": next(
            filter(
                lambda patientNaam: patientNaam.get("id")
                == mostRecentMessageRaw.recipient_id,
                PatientNamen,
            )
        ).get("name"),
    }
    return render_template(
        "addNewMessage.html",
        patienten=PatientNamen,
        lastMessage=lastMessage,
        views=views,
    )


# deze post route gebruikt de data in de meegestuurde form om een nieuw berichtje aan te maken via de backend
@views.route("/postNewMessage", methods=["POST"])
def postNewMessage():
    # bouwt de message op op basis van de data in de meegestuurde form
    newMessage = MessagePost(
        recipient_id=int(request.form["recipientId"]),
        content=Content(text=str(request.form["message"])),
    )
    # stuurt de opgebouwde message door naar de backend laag en geeft een passend bericht op basis van de feedback(true bij succes of false bij mislukking)
    if Messages.PostNewMessage(newMessage):
        return render_template(
            "genericMessage.html",
            message="berichtje is succesvol aangemaakt",
            views=views,
        )
    else:
        return render_template(
            "genericMessage.html",
            message="er is een fout opgetreden bij het doorsturen naar de bewell api",
            views=views,
        )

flask-app/webui/templates/addNewMessage.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<h3 class="" align="center">Nieuw Berichtje</h3>

<form class="" method="post" action="{{ url_for('views.postNewMessage') }}">
  <div class="form-group form-row">
    <label for="recipientId" class="col col-form-label">recipientId</label>
    <div class="col">
      <input type="" class="" id="recipientId" name="recipientId" placeholder="recipientId">
    </div>
  </div>
  <div class="form-group row">
    <label for="message" class="col col-form-label">message</label>
    <div class="col">
      <input type="text" class="" id="message" name="message" placeholder="message">
    </div>
  </div>
  <div class="form-group row">
    <button class="col btn btn-outline-primary btn-sm border-dark text-dark p-1 m-0" type="submit">aanmaken</button>
  </div>
</form>
<br>
<h5 align="center">meest recent berichtje</h5>
<table class="table table-sm table-bordered table-hover table-responsive-sm">
  <tbody>
    <tr>
      <td scope="row">{{ lastMessage.inhoud }}</td>
      <td>{{ lastMessage.ontvanger }}</td>
    </tr>
  </tbody>
</table>

{% endblock %}

flask-app/webui/templates/addNewPatient.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<h1 align="center">Nieuwe Patient</h1>
<form class="" method="post" action="{{ url_for('views.newPatient') }}">
    <div class="form-group form-row">
        <label for="afdeling" class="col col-form-label">afdeling</label>
        <div class="col">
          <input type="number" class="" id="afdeling" name="afdeling" placeholder="afdelingsNummer">
        </div>
    </div>
    <div class="form-group row">
      <label for="kamer" class="col col-form-label">kamernummer</label>
      <div class="col">
        <input type="number" class="" id="kamer" name="kamer" placeholder="kamernummer">
      </div>
    </div>
    <div class="form-group row">
      <label for="kamer" class="col col-form-label">familienaam</label>
      <div class="col">
        <input type="text" class="" id="familienaam" name="familienaam" placeholder="familienaam">
      </div>
    </div>
    <div class="form-group row">
      <label for="kamer" class="col col-form-label">voornaam</label>
      <div class="col">
        <input type="text" class="" id="voornaam" name="voornaam" placeholder="voornaam">
      </div>
    </div>
    <div class="form-group row">
      <label for="kamer" class="col col-form-label">geboortedatum</label>
      <div class="col">
        <input type="date"  class="" id="geboortedatum" name="geboortedatum" placeholder="01/01/2000">
      </div>
    </div>
    <div class="form-group row">
      <label for="kamer" class="col col-form-label">dieet</label>
      <div class="col">
        <input type="text" class="" id="dieet" name="dieet" placeholder="gewoon">
      </div>
    </div>
    <div class="form-group row">
      <button class="btn btn-primary" type="submit">aanmaken</button>
    </div>
</form>
    

{% endblock %}

flask-app/webui/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}Home{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">StageApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Usecase 1
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/getNewMessage">nieuw berichtje</a></li>
              
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Usecase 2
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/usecase2">Patientenlijst</a></li>
              
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


  <div class="container">{% block content %} {% endblock %}</div>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  {% block scripts %} {% endblock %}

</body>
</html>

flask-app/webui/templates/genericMessage.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<h1 align="center">{{message}}</h1>
{% endblock %}

flask-app/webui/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<h1 align="center">Usecases</h1>

    <p>Via tabladen kan naar de usecases genavigeerd worden</p>
    <p>Bij problemen, laat maar weten...</p>
    

{% endblock %}

flask-app/webui/templates/usecase1.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<h1 align="center">Nieuw bericht</h1>
<form class="" method="post" action="{{ url_for('views.newMessage') }}">
    <div class="form-group form-row">
        <label for="recipient_id" class="col col-form-label">id ontvanger</label>
        <div class="col">
          <input type="number" class="" id="recipient_id" name="recipient_id" placeholder="ontvanger id">
        </div>
    </div>
    <div class="form-group row">
      <label for="kamer" class="col col-form-label">inhoud</label>
      <div class="col">
        <input type="number" class="" id="content" name="content" placeholder="inhoud">
      </div>
    </div>
</form>
    

{% endblock %}

flask-app/webui/templates/usecase2.html
{% extends "base.html" %} {% block title %}UseCase2{% endblock %} {% block content%}
<head>
  <script src="{{url_for('static', filename='usecase2.js')}}"></script>
</head>
<h1 align="center">Usecase 2</h1>

<!--code om met sqllite db te werken ipv api-->
<!-- <form action="{{ url_for('views.addDummyData') }}" method="post">
  <button type="submit" class="btn btn-primary">Voeg dummiedata toe</button>
</form>
<form action="{{ url_for('views.deleteData') }}" method="post">
  <button type="submit" class="btn btn-primary">reset data</button>
</form> -->
<form action="{{ url_for('views.addPatientRequest') }}" method="get">
  <button type="submit" class="btn btn-primary">nieuwe patient</button>
</form>

<form class="input-group" action="{{ url_for('views.filterData') }}" method="post">
  <input id="searchQuery" name="searchQuery" type="text" required class="form-control rounded" placeholder="patient" value="{{searchValue if searchValue is defined else ''}}" ></input>
  <button type="Submit" class="btn btn-outline-primary">search</button>
</form>

<br>
{%if not patients or patients|length==0%}
<p class="" align="center">Geen patienten gevonden</p>
{%else %}


<table class="table table-sm table-bordered table-hover table-responsive-sm">
  <thead>
      <tr>
          <th scope="col">Afdeling</th>
          <th scope="col">Kamer</th>
          <th scope="col">Familienaam</th>
          <th scope="col">Voornaam</th>
          <th scope="col">Geboortedatum</th>
          <th scope="col">Geslacht</th>
          <th scope="col">Nationaliteit</th>
          <th scope="col" name="deleteheader"></th>
      </tr>
  </thead>
  <tbody>
      {% for patient in patients %}
      <tr>
          <td scope="row">{{ patient.box_code }}</td>
          <td>{{ patient.kamer }}</td>
          <td>{{ patient.last_name }}</td>
          <td>{{ patient.first_name }}</td>
          <td>{{ patient.date_of_birth }}</td>
          <td>{{ patient.gender }}</td>
          <td>{{ patient.nationality }}</td>
          <td>
              <form action="{{ url_for('views.deleteRecord', patientId=patient.id) }}" method="post">
                  <button type="submit"><i class="bi bi-trash"></i></button>
              </form>
          </td>
      </tr>
      {% endfor %}
  </tbody>
</table>
{%endif%}
{% endblock %}